### ISSUE TITLE
needs improved documentation

### ISSUE THREAD

**Issue by homberghp** [prepare-assignment/core#36]
# Building without hand holding please.

The installation instructions are insufficient for non python developers.

Use one example project that has  a known to work content including the required prepare.yml file
which should work out of the box, after the user followed the instructions to the detail.

Now I get

![image](https://github.com/prepare-assignment/core/assets/4232630/e3bbe53f-8ec6-4fbb-8982-fddfa55d23b2)

which is a bummer.

**Comment by Bonajo** [comment]
The `uses` tag expects to be given a `task`, in this case `prc2-gradelist-assignment` is given, which is not a task.  
Tasks are for example [svg-darkmode](https://github.com/prepare-assignment/svg-darkmode) or [codestripper](https://github.com/prepare-assignment/codestripper).  This is also stated in the short documentation that is available.

But I will leave this issue open, as there is a need for more documentation.
