### ISSUE TITLE
Task fails when there are no test resources

### ISSUE THREAD

**Issue by lenntt** [prepare-assignment/core#39]
A project without test resources should be accepted (?).
Everything (the actions) continue, but I'd prefer to have a clean output without red error messages.

From the output:
```sh
DEBUG - Executing task 'Create test archive' (runner.py:43)
DEBUG - Executing task 'Create class archive' (runner.py:43)
DEBUG - Executing task 'Remove test resources' (runner.py:43)
	[TASK] ERROR - 'out/assignment/src/test/resources' doesn't match any files, set 'force' to ignore
'out/assignment/src/test/resources' doesn't match any files, set 'force' to ignore
DEBUG - ✓ Prepared :) (runner.py:130)
Error code: 1
```
Note, there are a few warnings earlier on this as well, perhaps at 'info' level would be better?
DEBUG - Executing task 'Copy main resources' (runner.py:43)
	[TASK] WARNING - Glob 'solution/src/main/resources' doesn't match any files
Glob 'solution/src/main/resources' doesn't match any files
DEBUG - Executing task 'Copy test resources' (runner.py:43)
	[TASK] WARNING - Glob 'solution/src/test/resources' doesn't match any files

to reproduce: run on a project without test resources.

**Comment by Bonajo** [comment]
Not part of 'core', problem with a custom action.
